language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
env:
  - CODECOV_TOKEN="d0a04170-cbf8-4e0b-93db-6fd6a4e2a7c6"
before_script:
  - npm install
script:
  - npm run cover
  - codecov
